//This sketch was created using the pov.py module to 
//fill the I2C EEPROM on the POV fan
//
//LED on Pin 13 blinks once data transfer is complete
//
//Connections required:
//	Fan			Arduino
//	DATA  <--->	Analog Pin 4
//	CLK   <--->	Analog Pin 5
//	Vcc   <--->	3.3V
//	GND   <--->	GND


#include <Wire.h>

void setup()
{
  Wire.begin();        // join i2c bus (address optional for master)
  pinMode(13, OUTPUT);    
}

void loop()
{ 
  Wire.beginTransmission(0x50);
  Wire.write(0);
  Wire.write(6);
  // ####################TESTING POV FAN####################
  Wire.write(15);
  //----------N----------
  Wire.write(0x80);
  Wire.write(0xF9);
  Wire.write(0xE3);
  Wire.write(0xCF);
  Wire.write(0x80);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  //----------F----------
  Wire.write(0xBF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(16);
  Wire.write(0x80);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  //----------V----------
  Wire.write(0x83);
  Wire.write(0xFD);
  Wire.write(0xFE);
  Wire.write(0xFD);
  Wire.write(0x83);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(32);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  //----------G----------
  Wire.write(0xF3);
  Wire.write(0xB5);
  Wire.write(0xB6);
  Wire.write(0xBC);
  Wire.write(0xC3);
  //----------N----------
  Wire.write(0x80);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(48);
  Wire.write(0xF9);
  Wire.write(0xE3);
  Wire.write(0xCF);
  Wire.write(0x80);
  //----------I----------
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  Wire.write(0xBE);
  Wire.write(0xBE);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------S----------
  Wire.write(0xD9);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(64);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xCD);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  // ####################NEW SOFTWARE UPDATE####################
  Wire.write(19);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(80);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  //----------D----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(96);
  Wire.write(0xBE);
  Wire.write(0x80);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------U----------
  Wire.write(0x81);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0x81);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(112);
  Wire.write(0xFF);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------R----------
  Wire.write(0xDE);
  Wire.write(0xAD);
  Wire.write(0xAB);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(128);
  //----------W----------
  Wire.write(0x80);
  Wire.write(0xFD);
  Wire.write(0xFB);
  Wire.write(0xFD);
  Wire.write(0x80);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------F----------
  Wire.write(0xBF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------O----------
  Wire.write(0xE3);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(144);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------S----------
  Wire.write(0xD9);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xCD);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  //----------W----------
  Wire.write(0x80);
  Wire.write(0xFD);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(160);
  Wire.write(0xFB);
  Wire.write(0xFD);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------N----------
  Wire.write(0x80);
  Wire.write(0xF9);
  Wire.write(0xE3);
  Wire.write(0xCF);
  Wire.write(0x80);
  // ####################CAPITALIZE LOWERCASE####################
  Wire.write(20);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(176);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------S----------
  Wire.write(0xD9);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xCD);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  //----------C----------
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(192);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------R----------
  Wire.write(0xDE);
  Wire.write(0xAD);
  Wire.write(0xAB);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------W----------
  Wire.write(0x80);
  Wire.write(0xFD);
  Wire.write(0xFB);
  Wire.write(0xFD);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(208);
  Wire.write(0x80);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------L----------
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0x80);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(224);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------Z----------
  Wire.write(0x9E);
  Wire.write(0xAE);
  Wire.write(0xB6);
  Wire.write(0xBA);
  Wire.write(0xBC);
  //----------I----------
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  Wire.write(0xBE);
  Wire.write(0xBE);
  //----------L----------
  Wire.write(0xFE);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x50);
  Wire.write(240);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0x80);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------I----------
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(0);
  Wire.write(0x80);
  Wire.write(0xBE);
  Wire.write(0xBE);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------A----------
  Wire.write(0xE0);
  Wire.write(0xDB);
  Wire.write(0xBB);
  Wire.write(0xDB);
  Wire.write(0xE0);
  //----------C----------
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(16);
  Wire.write(0xDD);
  Wire.write(0xE3);
  // ####################PYTHON POWERED####################
  Wire.write(14);
  //----------D----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------R----------
  Wire.write(0xDE);
  Wire.write(0xAD);
  Wire.write(0xAB);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(32);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------W----------
  Wire.write(0x80);
  Wire.write(0xFD);
  Wire.write(0xFB);
  Wire.write(0xFD);
  Wire.write(0x80);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(48);
  Wire.write(0xE3);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //---------- ----------
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  Wire.write(0xFF);
  //----------N----------
  Wire.write(0x80);
  Wire.write(0xF9);
  Wire.write(0xE3);
  Wire.write(0xCF);
  Wire.write(0x80);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(64);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------H----------
  Wire.write(0x80);
  Wire.write(0xF7);
  Wire.write(0xF7);
  Wire.write(0xF7);
  Wire.write(0x80);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------Y----------
  Wire.write(0x8F);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(80);
  Wire.write(0xEF);
  Wire.write(0xE0);
  Wire.write(0xEF);
  Wire.write(0x8F);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  // ####################ZJEMBEDDED####################
  Wire.write(10);
  //----------D----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(96);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------D----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  //----------D----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xBE);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(112);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------B----------
  Wire.write(0xF9);
  Wire.write(0xC6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------M----------
  Wire.write(0x80);
  Wire.write(0xDF);
  Wire.write(0xEF);
  Wire.write(0xDF);
  Wire.write(0x80);
  //----------E----------
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(128);
  Wire.write(0xB6);
  Wire.write(0x80);
  //----------J----------
  Wire.write(0x81);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFD);
  //----------Z----------
  Wire.write(0x9E);
  Wire.write(0xAE);
  Wire.write(0xB6);
  Wire.write(0xBA);
  Wire.write(0xBC);
  // ####################BLOGSPOT####################
  Wire.write(8);
  //----------T----------
  Wire.write(0xBF);
  Wire.write(0xBF);
  Wire.write(0x80);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(144);
  Wire.write(0xBF);
  Wire.write(0xBF);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------P----------
  Wire.write(0xCF);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0xB7);
  Wire.write(0x80);
  //----------S----------
  Wire.write(0xD9);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(160);
  Wire.write(0xCD);
  //----------G----------
  Wire.write(0xF3);
  Wire.write(0xB5);
  Wire.write(0xB6);
  Wire.write(0xBC);
  Wire.write(0xC3);
  //----------O----------
  Wire.write(0xE3);
  Wire.write(0xDD);
  Wire.write(0xBE);
  Wire.write(0xDD);
  Wire.write(0xE3);
  //----------L----------
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0xFE);
  Wire.write(0x80);
  Wire.endTransmission();
  delay(500);
  Wire.beginTransmission(0x51);
  Wire.write(176);
  //----------B----------
  Wire.write(0xF9);
  Wire.write(0xC6);
  Wire.write(0xB6);
  Wire.write(0xB6);
  Wire.write(0x80);
  Wire.endTransmission();

  while(1){
    digitalWrite(13, HIGH);   // set the LED on
    delay(1000);              // wait for a second
    digitalWrite(13, LOW);    // set the LED off
    delay(1000);              // wait for a second
  }
}
